"""Private local FN/realm controller; uses Python and Windows APIs, never PowerShell."""
import argparse
from contextlib import ExitStack
import ctypes as C
from ctypes import wintypes as W
from datetime import datetime, timezone
import hashlib
import importlib.util
import ipaddress
import json
import os
from pathlib import Path
import re
import secrets
import socket
import subprocess
import sys
import time
import urllib.request

DOTNET_FILETIME_OFFSET = 504911232000000000
LISTEN_MARKER = '// Generated by the local host launcher after FN validation.'


def read_json(path, default=None):
    return json.loads(path.read_text(encoding='utf-8-sig')) if path.exists() else default


def write_json(path, value):
    temporary = path.with_suffix(path.suffix + '.tmp')
    with temporary.open('w', encoding='utf-8') as output:
        json.dump(value, output, indent=2)
        output.flush()
        os.fsync(output.fileno())
    os.replace(temporary, path)


class Windows:
    """Pointer-sized ctypes declarations also work in the bundled 32-bit Python."""
    def __init__(self):
        self.k = C.WinDLL('kernel32', use_last_error=True)
        self.k.OpenProcess.argtypes = [W.DWORD, W.BOOL, W.DWORD]
        self.k.OpenProcess.restype = W.HANDLE
        self.k.CloseHandle.argtypes = [W.HANDLE]
        self.k.CloseHandle.restype = W.BOOL
        self.k.QueryFullProcessImageNameW.argtypes = [W.HANDLE, W.DWORD, W.LPWSTR, C.POINTER(W.DWORD)]
        self.k.QueryFullProcessImageNameW.restype = W.BOOL
        self.k.GetProcessTimes.argtypes = [W.HANDLE] + [C.POINTER(W.FILETIME)] * 4
        self.k.GetProcessTimes.restype = W.BOOL
        self.k.GetExitCodeProcess.argtypes = [W.HANDLE, C.POINTER(W.DWORD)]
        self.k.GetExitCodeProcess.restype = W.BOOL
        self.k.TerminateProcess.argtypes = [W.HANDLE, W.UINT]
        self.k.TerminateProcess.restype = W.BOOL
        self.k.WaitForSingleObject.argtypes = [W.HANDLE, W.DWORD]
        self.k.WaitForSingleObject.restype = W.DWORD
        self.k.CreateFileW.argtypes = [W.LPCWSTR, W.DWORD, W.DWORD, W.LPVOID, W.DWORD, W.DWORD, W.HANDLE]
        self.k.CreateFileW.restype = W.HANDLE
        self.k.CreateToolhelp32Snapshot.argtypes = [W.DWORD, W.DWORD]
        self.k.CreateToolhelp32Snapshot.restype = W.HANDLE
        self.ip = C.WinDLL('iphlpapi', use_last_error=True)
        self.ip.GetExtendedUdpTable.argtypes = [W.LPVOID, C.POINTER(W.DWORD), W.BOOL, W.ULONG, C.c_int, W.ULONG]
        self.ip.GetExtendedUdpTable.restype = W.DWORD

    def _record(self, handle, pid):
        exit_code = W.DWORD()
        if not self.k.GetExitCodeProcess(handle, C.byref(exit_code)):
            raise C.WinError(C.get_last_error())
        if exit_code.value != 259:
            return None
        path = C.create_unicode_buffer(32768)
        count = W.DWORD(len(path))
        if not self.k.QueryFullProcessImageNameW(handle, 0, path, C.byref(count)):
            raise C.WinError(C.get_last_error())
        created, exited, kernel, user = (W.FILETIME() for _ in range(4))
        if not self.k.GetProcessTimes(handle, C.byref(created), C.byref(exited), C.byref(kernel), C.byref(user)):
            raise C.WinError(C.get_last_error())
        ticks = (created.dwHighDateTime << 32) + created.dwLowDateTime + DOTNET_FILETIME_OFFSET
        return dict(id=int(pid), path=path.value, startTicks=str(ticks))

    def record(self, pid):
        handle = self.k.OpenProcess(0x1000, False, int(pid))
        if not handle:
            if C.get_last_error() == 87:  # The PID no longer exists.
                return None
            raise C.WinError(C.get_last_error())
        try:
            return self._record(handle, pid)
        finally:
            self.k.CloseHandle(handle)

    def owned(self, expected):
        return bool(expected and self.same(expected, self.record(expected['id'])))

    @staticmethod
    def same(expected, actual):
        return bool(actual and int(expected['id']) == actual['id'] and
                    os.path.normcase(expected['path']) == os.path.normcase(actual['path']) and
                    str(expected['startTicks']) == actual['startTicks'])

    def terminate(self, expected):
        handle = self.k.OpenProcess(0x1000 | 0x100000 | 1, False, int(expected['id']))
        if not handle:
            if C.get_last_error() == 87:
                return
            raise C.WinError(C.get_last_error())
        try:
            if not self.same(expected, self._record(handle, expected['id'])):
                raise RuntimeError('Process ownership changed; it was not terminated.')
            if not self.k.TerminateProcess(handle, 0):
                raise C.WinError(C.get_last_error())
            if self.k.WaitForSingleObject(handle, 10000) != 0:
                raise RuntimeError('The owned FN process has not exited; host state was retained.')
        finally:
            self.k.CloseHandle(handle)

    def udp(self):
        size = W.DWORD()
        result = self.ip.GetExtendedUdpTable(None, C.byref(size), False, 2, 1, 0)
        if result not in (0, 122):
            raise C.WinError(result)
        for _ in range(3):
            buffer = C.create_string_buffer(size.value)
            result = self.ip.GetExtendedUdpTable(buffer, C.byref(size), False, 2, 1, 0)
            if result == 122:
                continue
            if result:
                raise C.WinError(result)
            count = W.DWORD.from_buffer(buffer).value
            class Row(C.Structure):
                _fields_ = [('address', W.DWORD), ('port', W.DWORD), ('pid', W.DWORD)]
            return [(socket.ntohs(row.port & 0xffff), int(row.pid))
                    for row in (Row * count).from_buffer(buffer, C.sizeof(W.DWORD))]
        raise RuntimeError('UDP process inventory changed repeatedly; retry the host command.')

    def lock(self, path):
        handle = self.k.CreateFileW(str(path), 0x80000000 | 0x40000000, 0, None, 4, 0x80, None)
        if handle == W.HANDLE(-1).value:
            raise RuntimeError('Another host command is running, or the extracted folder is not writable.')
        return handle

    def game_processes(self):
        class Entry(C.Structure):
            _fields_ = [('size', W.DWORD), ('usage', W.DWORD), ('pid', W.DWORD),
                        ('heap', C.c_size_t), ('module', W.DWORD), ('threads', W.DWORD),
                        ('parent', W.DWORD), ('priority', W.LONG), ('flags', W.DWORD),
                        ('exe', W.WCHAR * 260)]
        self.k.Process32FirstW.argtypes = [W.HANDLE, C.POINTER(Entry)]
        self.k.Process32FirstW.restype = W.BOOL
        self.k.Process32NextW.argtypes = [W.HANDLE, C.POINTER(Entry)]
        self.k.Process32NextW.restype = W.BOOL
        handle = self.k.CreateToolhelp32Snapshot(2, 0)
        if handle == W.HANDLE(-1).value:
            raise C.WinError(C.get_last_error())
        result, entry = [], Entry()
        entry.size = C.sizeof(Entry)
        try:
            found = self.k.Process32FirstW(handle, C.byref(entry))
            while found:
                if entry.exe.lower() == 'xash3d.exe':
                    record = self.record(entry.pid)
                    if record:
                        result.append(record)
                found = self.k.Process32NextW(handle, C.byref(entry))
        finally:
            self.k.CloseHandle(handle)
        return result


class Host:
    def __init__(self, bundle, version, first_port=27025, bind='0.0.0.0', windows=None):
        self.bundle = Path(bundle).resolve()
        self.version = version
        self.root = self.bundle / ('Stable-Base' if version == 'stable' else 'Portable-Package')
        self.game = self.root / 'game'
        self.exe = self.game / 'xash3d.exe'
        self.python = self.root / 'runtime/python.exe'
        self.state_path = self.root / 'host-state.json'
        self.settings_path = self.root / 'host-settings.json'
        self.config = read_json(self.root / 'FN/config.json')
        if self.config['bind'] != '127.0.0.1':
            raise ValueError('FN must be configured on 127.0.0.1.')
        if not 1024 <= int(self.config['port']) <= 65535:
            raise ValueError('Invalid FN port.')
        ipaddress.IPv4Address(bind)
        if not 1024 <= first_port <= 65525:
            raise ValueError('The first realm port must be between 1024 and 65525.')
        self.bind, self.first_port = bind, first_port
        self.win = windows or Windows()
        self.state = read_json(self.state_path, {})
        spec = importlib.util.spec_from_file_location('local_game_query', self.root / 'FN/game_query.py')
        self.query = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.query)

    def settings(self, create=False):
        settings = read_json(self.settings_path)
        if settings is None and create:
            settings = dict(version=2, public=True, servers=[
                dict(id='realm-' + suffix, hostname='[FN] MSR Realm ' + label,
                     port=self.first_port + offset, map='edana', maxplayers=10,
                     rcon_password=secrets.token_hex(24))
                for suffix, label, offset in [('one', 'One', 0), ('two', 'Two', 10)]])
            write_json(self.settings_path, settings)
        if not settings or len(settings.get('servers', [])) != 2:
            raise ValueError('Two realm settings are required. Start the local host first.')
        ports = []
        for server in settings['servers']:
            if not re.fullmatch(r'[a-z0-9-]+', server['id']):
                raise ValueError('Invalid realm id.')
            if not re.fullmatch(r'[A-Za-z0-9_-]+', server['map']):
                raise ValueError('Invalid map name.')
            for key in ('hostname', 'rcon_password'):
                if not server[key] or any(c in server[key] for c in '"\r\n;'):
                    raise ValueError('Invalid realm configuration.')
            if not 1024 <= int(server['port']) <= 65535 or not 1 <= int(server['maxplayers']) <= 32:
                raise ValueError('Invalid realm port or player limit.')
            if not (self.game / ('msr/maps/' + server['map'] + '.bsp')).is_file():
                raise ValueError('Missing map: ' + server['map'])
            ports.append(int(server['port']))
        if len(set(ports)) != 2:
            raise ValueError('The realms must use different ports.')
        return settings['servers']

    def health(self):
        try:
            with urllib.request.urlopen('http://127.0.0.1:%s/health' % self.config['port'], timeout=2) as response:
                result = json.load(response)['data']
            return result.get('service') == 'FN' and result.get('private') is True
        except (OSError, ValueError, KeyError):
            return False

    def save_state(self):
        write_json(self.state_path, self.state)

    def configure_listen_server(self):
        if not self.win.owned(self.state.get('fn')) or not self.health():
            raise RuntimeError('This host\'s FN service is not verified and ready. Its state was retained.')
        approved = read_json(self.root / 'FN/content-manifest.json')
        with urllib.request.urlopen('http://127.0.0.1:%s/api/v2/internal/sc/%s' % (self.config['port'], approved['scripts_crc32']), timeout=3) as response:
            if json.load(response).get('data') is not True:
                raise RuntimeError('FN rejected this version of the game scripts.')
        (self.game / 'msr/private_fn_listen.cfg').write_text(
            LISTEN_MARKER + '\n'
            'ms_serverchar 3\nms_central_enabled 1\n'
            f'ms_central_addr "127.0.0.1:{self.config["port"]}"\n', encoding='ascii')

    def deactivate_listen_server(self):
        path = self.game / 'msr/private_fn_listen.cfg'
        if path.is_file() and path.read_text(encoding='utf-8-sig').startswith(LISTEN_MARKER + '\n'):
            path.write_text(LISTEN_MARKER + '\n// Local FN has stopped. Start the local host to enable it again.\n'
                            'ms_central_enabled 0\n', encoding='ascii')

    def live_realms(self, servers):
        ports = {int(server['port']) for server in servers}
        result = []
        for port, pid in self.win.udp():
            if port in ports:
                process = self.win.record(pid)
                if process and os.path.normcase(process['path']) == os.path.normcase(str(self.exe)):
                    result.append((port, pid))
        return result

    def run_python(self, script, *arguments):
        subprocess.run([str(self.python), str(self.root / 'FN' / script), *arguments],
                       cwd=self.root, check=True, creationflags=subprocess.CREATE_NO_WINDOW)

    def spawn(self, args, label, cwd):
        logs = self.root / 'logs'
        logs.mkdir(exist_ok=True)
        with (logs / (label + '-stdout.log')).open('ab') as output, (logs / (label + '-stderr.log')).open('ab') as errors:
            process = subprocess.Popen([str(item) for item in args], cwd=cwd,
                                       stdin=subprocess.DEVNULL, stdout=output, stderr=errors,
                                       creationflags=subprocess.CREATE_NO_WINDOW)
        record = self.win.record(process.pid)
        if not record:
            raise RuntimeError(label + ' exited during startup. See the logs folder.')
        return record

    def wait(self, predicate, seconds, description):
        deadline = time.monotonic() + seconds
        while time.monotonic() < deadline:
            if predicate():
                return
            time.sleep(0.25)
        raise RuntimeError(description + ' Host state was retained; see the logs folder.')

    def start(self):
        self.run_python('check_content.py')
        servers = self.settings(create=True)
        records = self.state.get('games', [])
        owned = {r['process']['id'] for r in records if self.win.owned(r['process'])}
        untracked = [(port, pid) for port, pid in self.live_realms(servers) if pid not in owned]
        if untracked:
            raise RuntimeError('Existing realm ownership could not be verified; host state was retained: ' + str(untracked))
        if owned:
            if len(owned) != 2:
                raise RuntimeError('Only part of the host is running. Stop it successfully before restarting.')
            self.configure_listen_server()
            print('Both local realms are already running.')
            return
        occupied = {port for port, _ in self.win.udp()}
        if any(int(server['port']) in occupied for server in servers):
            raise RuntimeError('A configured UDP realm port is occupied; no new servers were started.')
        fn = self.state.get('fn')
        if not self.win.owned(fn):
            if self.health():
                raise RuntimeError('The FN port belongs to another host. Stop that host or choose a separate FN configuration.')
            fn = self.spawn([self.python, self.root / 'FN/fn_server.py', 'serve'], 'FN', self.root)
        self.state = dict(fn=fn, games=[])
        self.save_state()
        self.wait(self.health, 15, 'FN did not become ready.')
        self.configure_listen_server()
        for server in servers:
            cfg_name = 'server_public_' + server['id'] + '.cfg'
            config = [f'hostname "{server["hostname"]}"', 'sv_password none',
                      f'rcon_password "{server["rcon_password"]}"', 'sv_lan 0', 'public 1',
                      'ms_serverchar 3', 'ms_central_enabled 1',
                      f'ms_central_addr "127.0.0.1:{self.config["port"]}"',
                      'ms_reset_if_empty 0', 'ms_timelimit 0', 'ms_dev_mode 0', 'exec server_core.cfg']
            (self.game / 'msr' / cfg_name).write_text('\n'.join(config) + '\n', encoding='ascii')
            process = self.spawn([self.exe, '-dedicated', '-console', '-game', 'msr', '-port', str(server['port']),
                                  '+ip', self.bind, '+maxplayers', str(server['maxplayers']), '+sv_lan', '0',
                                  '+public', '1', '+exec', cfg_name, '+map', server['map']], server['id'], self.game)
            self.state['games'].append(dict(id=server['id'], port=int(server['port']), map=server['map'],
                                            hostname=server['hostname'], process=process))
            self.save_state()

            def ready():
                if not self.win.owned(process):
                    raise RuntimeError(server['hostname'] + ' exited. See the logs folder.')
                try:
                    info = self.query.info(int(server['port']), timeout=0.5)
                    reply = self.query.rcon(int(server['port']), server['rcon_password'], 'status')
                    return info['folder'] == 'msr' and bool(re.search(r'map\s*:\s+\S+', reply))
                except (OSError, ValueError):
                    return False
            self.wait(ready, 60, server['hostname'] + ' did not finish loading.')
        print('Local FN and both password-free realms are ready.')
        for server in servers:
            print(server['hostname'] + ': UDP ' + str(server['port']))
        print('LAN players use this PC\'s LAN address. Internet hosting needs your own port forwarding or UDP tunnel.')

    def stop(self):
        servers = self.settings()
        settings_by_id = {server['id']: server for server in servers}
        for record in self.state.get('games', []):
            process = record['process']
            if self.win.owned(process):
                server = settings_by_id[record['id']]
                self.query.rcon(int(record['port']), server['rcon_password'], 'quit')
                self.wait(lambda: not self.win.owned(process), 15, 'A realm has not stopped; FN remains running.')
        remaining = self.live_realms(servers + self.state.get('games', []))
        if remaining:
            raise RuntimeError('Realms are still running; FN and host state were retained: ' + str(remaining))
        fn = self.state.get('fn')
        if fn:
            if not self.win.owned(fn):
                if self.health():
                    raise RuntimeError('FN ownership could not be verified; its state was retained.')
            else:
                self.run_python('fn_server.py', 'backup')
                self.win.terminate(fn)
        self.deactivate_listen_server()
        self.state_path.unlink(missing_ok=True)
        self.state = {}
        print('Local host stopped. FN character saves and backups are preserved.')

    def status(self):
        print('FN reachable: ' + str(self.health()))
        for server in self.settings():
            try:
                info = self.query.info(int(server['port']), timeout=1)
                print('%s: %s, %s/%s players, UDP %s' % (server['hostname'], info['map'], info['players'], info['maxplayers'], server['port']))
            except (OSError, ValueError):
                print(server['hostname'] + ': not responding on UDP ' + str(server['port']))

    def launch_client(self):
        address = '127.0.0.1:' + str(self.settings()[0]['port'])
        launcher = self.bundle / 'MSR-Launcher.exe'
        if not launcher.is_file():
            raise RuntimeError('MSR-Launcher.exe is missing. The host is running; install the complete launcher update to join.')
        subprocess.Popen([str(launcher), '--version', self.version, '--address', address], cwd=self.bundle)

    def rcon(self, server_id, command):
        if not re.fullmatch(r'(?:status|ms_dm_grant (?:[0-9]|[12][0-9]|3[01])|ms_dm_revoke|ms_event (?:status|on|off|clear|orcs|rats))', command):
            raise ValueError('That command is not available through the Dungeon Master launcher.')
        server = next((s for s in self.settings() if s['id'] == server_id), None)
        if server is None:
            raise ValueError('Unknown realm id.')
        record = next((r for r in self.state.get('games', []) if r['id'] == server_id), None)
        if not record or not self.win.owned(record['process']):
            raise RuntimeError('Start this local realm before using Dungeon Master controls.')
        print(self.query.rcon(int(server['port']), server['rcon_password'], command))


class Versions:
    """Switch stopped FN stores before a selected version can resume play."""
    def __init__(self, selected):
        self.selected = selected
        self.bundle = selected.bundle
        other = 'stable' if selected.version == 'enhanced' else 'enhanced'
        self.hosts = {selected.version: selected,
                      other: Host(self.bundle, other, selected.first_port, selected.bind, selected.win)}

    def validate_profiles(self):
        def unique_object(pairs):
            result = {}
            for key, value in pairs:
                if key in result:
                    raise ValueError('Duplicate JSON member')
                result[key] = value
            return result
        identities = []
        for version, host in self.hosts.items():
            path = host.root / 'player-profile.json'
            if not path.exists():
                continue
            try:
                value = json.loads(path.read_text(encoding='utf-8-sig'), object_pairs_hook=unique_object)
                identity = value['profile_key']
                if not isinstance(identity, str) or not re.fullmatch(r'[0-9a-f]{32}', identity):
                    raise ValueError('Invalid profile key')
            except (ValueError, KeyError, TypeError) as exc:
                raise RuntimeError(version.title() + ' has an invalid player-profile.json. Restore its backup before switching; no saves or profiles were changed.') from exc
            identities.append(identity)
        if len(set(identities)) > 1:
            raise RuntimeError('Stable and Enhanced have different player identities. Keep both profiles and restore the intended matching identity before switching; no saves or profiles were changed.')

    def verify_stable(self):
        manifest = read_json(self.bundle / 'Packaging-Work/stable-base-manifest.json')
        critical = {'game/xash3d.exe', 'game/msr/cl_dlls/client.dll', 'game/msr/dlls/ms.dll', 'game/msr/scripts.pak'}
        for relative in critical:
            path = self.hosts['stable'].root / relative
            expected = manifest['files'].get(relative, {}).get('sha256')
            if not expected or not path.is_file():
                raise RuntimeError('Stable base verification is incomplete: ' + relative)
            with path.open('rb') as stream:
                actual = hashlib.file_digest(stream, 'sha256').hexdigest()
            if actual != expected:
                raise RuntimeError('Stable base differs from its preserved original: ' + relative)
        print('Stable base verified: all four critical original files match.')

    def current_version(self):
        active = read_json(self.bundle / 'active-version.json', {'version': 'Enhanced'})
        current = str(active.get('version', '')).lower()
        if current not in self.hosts:
            raise RuntimeError('Invalid active-version.json; no saves were transferred.')
        running = set()
        owned = {}
        for version, host in self.hosts.items():
            for record in host.state.get('games', []):
                if host.win.owned(record['process']):
                    owned[record['process']['id']] = version
                    running.add(version)
            fn = host.state.get('fn')
            if fn:
                if host.win.owned(fn):
                    running.add(version)
                elif host.win.record(fn['id']):
                    raise RuntimeError('FN ownership is ambiguous. Stop the original host successfully before switching.')
        paths = {os.path.normcase(str(host.exe)): version for version, host in self.hosts.items()}
        for process in self.selected.win.game_processes():
            version = paths.get(os.path.normcase(process['path']))
            if version is not None and owned.get(process['id']) != version:
                raise RuntimeError('Close the game before starting or switching local hosts. An open client or unverified server was left untouched.')
        if len(running) > 1:
            raise RuntimeError('Both versions have running host processes. Stop one host before switching save sets.')
        return next(iter(running)) if running else current

    def transfer(self, source, target):
        for host in (source, target):
            if Path(host.config['database']).as_posix() != 'data/FN.sqlite3':
                raise RuntimeError('Automatic switching requires the packaged FN database location; no saves were transferred.')
        src = source.root / 'FN/data/FN.sqlite3'
        dst = target.root / 'FN/data/FN.sqlite3'
        if not src.exists() and dst.exists():
            raise RuntimeError('The active version has no FN database, but the selected version has saves. Existing saves were preserved; choose the intended active version before switching.')
        for host, database in ((source, src), (target, dst)):
            if not database.exists():
                host.run_python('fn_server.py', 'list')
                if not database.is_file():
                    raise RuntimeError('FN did not initialize the expected database; no saves were transferred.')
        script = self.bundle / 'Packaging-Work/transfer_fn_state.py'
        if not script.is_file():
            raise RuntimeError('The save-transfer helper is missing. Restore the full package before switching.')
        subprocess.run([str(source.python), str(script), str(source.root), str(target.root), str(self.bundle / 'Version-Backups')],
                       cwd=self.bundle, check=True, creationflags=subprocess.CREATE_NO_WINDOW)

    def start(self, play=False):
        # Match the original switcher's lock order; lock both versions so another
        # controller cannot start FN while the databases are being copied.
        with ExitStack() as stack:
            for path in [self.bundle / 'version-switch.lock'] + [self.hosts[v].root / 'host.lock' for v in ('enhanced', 'stable')]:
                handle = self.selected.win.lock(path)
                stack.callback(self.selected.win.k.CloseHandle, handle)
            # The native client launcher uses the same lock while creating or
            # copying profiles. Hold it through transfer and release before play.
            profile_lock = self.selected.win.lock(self.bundle / '.player-profile.lock')
            try:
                self.validate_profiles()
                for host in self.hosts.values():
                    host.state = read_json(host.state_path, {})
                if self.selected.version == 'stable':
                    self.verify_stable()
                current = self.current_version()
                if current != self.selected.version:
                    source = self.hosts[current]
                    if source.state:
                        source.stop()
                    # Even a state-less source must be checked before touching its DB.
                    if source.live_realms(source.settings(create=True)) or source.health():
                        raise RuntimeError('The source host is still reachable. Its saves were not transferred.')
                    self.transfer(source, self.selected)
                # Record the selected save store before starting it: if loading later
                # fails, the next launch must not overwrite it from a stale version.
                write_json(self.bundle / 'active-version.json', dict(version=self.selected.version.title(), switched=datetime.now(timezone.utc).isoformat()))
                self.selected.start()
            finally:
                self.selected.win.k.CloseHandle(profile_lock)
            print('Active version: ' + self.selected.version.title())
            if play:
                self.selected.launch_client()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--package-root', type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument('--version', choices=['enhanced', 'stable'], default='enhanced')
    parser.add_argument('--action', choices=['start', 'stop', 'status', 'play', 'rcon'], required=True)
    parser.add_argument('--first-port', type=int, default=27025)
    parser.add_argument('--bind', default='0.0.0.0')
    parser.add_argument('--server-id', choices=['realm-one', 'realm-two'], default='realm-one')
    parser.add_argument('--command', default='status')
    args = parser.parse_args()
    try:
        host = Host(args.package_root, args.version, args.first_port, args.bind)
        if args.action in ('start', 'play'):
            Versions(host).start(play=args.action == 'play')
            return 0
        lock = host.win.lock(host.root / 'host.lock')
        try:
            if args.action == 'rcon':
                host.rcon(args.server_id, args.command)
            else:
                getattr(host, args.action)()
        finally:
            host.win.k.CloseHandle(lock)
        return 0
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError) as exc:
        print('Host error: ' + str(exc), file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
