// Original generated Daragoth foliage. +Z up, ground origin Z=0.
$modelname "plains_grass.mdl"
$cd "."
$cdtexture "."
$scale 1
$gamma 1.8
$origin 0 0 0 -90
$body "prop" "plains_grass_reference"
$sequence "idle" "plains_grass_idle" fps 12 loop
$bbox -23.5805 -23.3572 0.0000 22.4725 21.0283 30.0000
$cbox -23.5805 -23.3572 0.0000 22.4725 21.0283 30.0000
$texrendermode "plains_grass_blades.bmp" masked
