// Original generated Daragoth foliage. +Z up, ground origin Z=0.
$modelname "plains_pine.mdl"
$cd "."
$cdtexture "."
$scale 1
$gamma 1.8
$origin 0 0 0 -90
$body "prop" "plains_pine_reference"
$sequence "idle" "plains_pine_idle" fps 12 loop
$bbox -157.0066 -156.5361 0.0000 157.2070 164.3978 520.0000
$cbox -157.0066 -156.5361 0.0000 157.2070 164.3978 520.0000
$texrendermode "pine_needles.bmp" masked
