// Original generated Daragoth foliage. +Z up, ground origin Z=0.
$modelname "plains_birch.mdl"
$cd "."
$cdtexture "."
$scale 1
$gamma 1.8
$origin 0 0 0 -90
$body "prop" "plains_birch_reference"
$sequence "idle" "plains_birch_idle" fps 12 loop
$bbox -100.6093 -97.3991 0.0000 102.4658 97.4484 430.0000
$cbox -100.6093 -97.3991 0.0000 102.4658 97.4484 430.0000
$texrendermode "birch_leaves.bmp" masked
