// Generated by tools/prepare_historical_worldmap.py; approximate named regions only.
#pragma once
namespace MSRWorldChart {
struct Pin { const char* id; float u, v; };
struct Tile { const char* file; int x, y; };
static const int width = 4096, height = 3884, tileSize = 1024;
static const Pin pins[] = {
    {"edana", 0.392835083f, 0.526041667f},
    {"thornlands", 0.382334775f, 0.510416667f},
    {"mscave", 0.400247066f, 0.506510417f},
    {"heras", 0.409512044f, 0.459635417f},
    {"gertenheld_cape", 0.351451513f, 0.443359375f},
    {"ara", 0.302038295f, 0.481119792f},
    {"sfor", 0.447189623f, 0.490885417f},
    {"calruin2", 0.470043237f, 0.496744792f},
    {"helena", 0.378011118f, 0.537760417f},
    {"bloodrose", 0.408894379f, 0.552083333f},
    {"deralia", 0.348363187f, 0.522786458f},
    {"daragoth", 0.284126004f, 0.594401042f},
    {"the_wall", 0.502779494f, 0.386718750f},
    {"the_wall2", 0.502779494f, 0.386718750f},
    {"tundra", 0.418777023f, 0.339843750f},
    {"aluhandra2", 0.386040766f, 0.678385417f},
    {"shad_palace", 0.302038295f, 0.705078125f},
    {"aleyesu", 0.274861025f, 0.758463542f},
    {"ms_wicardoven", 0.523162446f, 0.466796875f},
};
static const int pinCount = sizeof(pins)/sizeof(pins[0]);
static const Tile tiles[] = {
    {"gfx/vgui/msr_world_atlas_0_0.tga", 0, 0},
    {"gfx/vgui/msr_world_atlas_1_0.tga", 1024, 0},
    {"gfx/vgui/msr_world_atlas_2_0.tga", 2048, 0},
    {"gfx/vgui/msr_world_atlas_3_0.tga", 3072, 0},
    {"gfx/vgui/msr_world_atlas_0_1.tga", 0, 1024},
    {"gfx/vgui/msr_world_atlas_1_1.tga", 1024, 1024},
    {"gfx/vgui/msr_world_atlas_2_1.tga", 2048, 1024},
    {"gfx/vgui/msr_world_atlas_3_1.tga", 3072, 1024},
    {"gfx/vgui/msr_world_atlas_0_2.tga", 0, 2048},
    {"gfx/vgui/msr_world_atlas_1_2.tga", 1024, 2048},
    {"gfx/vgui/msr_world_atlas_2_2.tga", 2048, 2048},
    {"gfx/vgui/msr_world_atlas_3_2.tga", 3072, 2048},
    {"gfx/vgui/msr_world_atlas_0_3.tga", 0, 3072},
    {"gfx/vgui/msr_world_atlas_1_3.tga", 1024, 3072},
    {"gfx/vgui/msr_world_atlas_2_3.tga", 2048, 3072},
    {"gfx/vgui/msr_world_atlas_3_3.tga", 3072, 3072},
};
static const int tileCount = sizeof(tiles)/sizeof(tiles[0]);
}
