#!/usr/bin/env python3
"""Generate conservative PrimeXT material metadata for MSR studio models."""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


STUDIO_IDENT = b"IDST"
STUDIO_VERSION = 10
TEXTURE_COUNT_OFFSET = 180
TEXTURE_INDEX_OFFSET = 184
TEXTURE_RECORD_SIZE = 80


def classify(model_path: Path, texture_name: str) -> tuple[str, float, float]:
    value = f"{model_path.as_posix()} {texture_name}".lower()

    if any(word in value for word in ("glass", "crystal", "gem", "jewel")):
        return "glass", 0.86, 0.24
    if any(word in value for word in ("blade", "sword", "axe", "metal", "steel", "iron", "chain", "helm", "armor", "shield")):
        return "metal", 0.68, 0.30
    if any(word in value for word in ("wood", "bow", "staff", "club", "handle", "haft")):
        return "wood", 0.24, 0.04
    if any(word in value for word in ("leaf", "grass", "plant", "tree", "vine", "moss")):
        return "grass", 0.10, 0.01
    if any(word in value for word in ("rock", "stone", "dirt", "ground", "earth")):
        return "dirt", 0.16, 0.01
    if any(word in value for word in ("cloth", "robe", "gown", "leather", "hide", "fur", "skin", "body", "face")):
        return "default", 0.18, 0.01
    return "default", 0.26, 0.03


def model_textures(path: Path) -> list[str]:
    data = path.read_bytes()
    if len(data) < TEXTURE_INDEX_OFFSET + 4 or data[:4] != STUDIO_IDENT:
        return []
    if struct.unpack_from("<i", data, 4)[0] != STUDIO_VERSION:
        return []

    count = struct.unpack_from("<i", data, TEXTURE_COUNT_OFFSET)[0]
    offset = struct.unpack_from("<i", data, TEXTURE_INDEX_OFFSET)[0]
    if count <= 0 or count > 4096 or offset <= 0:
        return []
    if offset + count * TEXTURE_RECORD_SIZE > len(data):
        return []

    names: list[str] = []
    for index in range(count):
        start = offset + index * TEXTURE_RECORD_SIZE
        raw = data[start : start + 64].split(b"\0", 1)[0]
        name = raw.decode("latin-1", errors="ignore").strip()
        if name:
            names.append(Path(name.replace("\\", "/")).stem)
    return names


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("models", type=Path, help="MSR models directory")
    parser.add_argument("output", type=Path, help="generated .mat file")
    args = parser.parse_args()

    models_root = args.models.resolve()
    records: dict[str, tuple[str, float, float]] = {}
    parsed_models = 0

    for model in sorted(models_root.rglob("*.mdl")):
        textures = model_textures(model)
        if not textures:
            continue
        parsed_models += 1
        relative = model.relative_to(models_root)
        model_name = model.stem
        for texture in textures:
            key = f"{model_name}/{texture}"
            records.setdefault(key, classify(relative, texture))

    lines = [
        "// Generated by msr_port/generate_msr_materials.py.",
        "// These conservative values add material response without changing gameplay.",
        "",
    ]
    for key in sorted(records, key=str.casefold):
        material, smoothness, reflection = records[key]
        lines.extend(
            (
                f'"{key}"',
                "{",
                f'    "material"     "{material}"',
                f'    "smoothness"   "{smoothness:.2f}"',
                f'    "reflectScale" "{reflection:.2f}"',
                "}",
                "",
            )
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Parsed {parsed_models} models and wrote {len(records)} material bindings to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
