{
const SPRITE_LIGHTNING lgtning.spr
const SPRITE_GLOW 3dmflaora.spr
const GLOW_DURATION 3
const OFS_POS 5
const OFS_NEG -5
const LIGHT_RADIUS 128
const LIGHT_COLOR (100,33,253)
}
{ game_precache
precache SPRITE_GLOW
precache SPRITE_LIGHTNING
}
#include items/magic_hand_base_cl
{ cl_handmagic_beam
if ( PARAM1 equals 'hands' )
{
setvard magichand.on 1
setvard handmagic.handid game.localplayer.viewmodel.active.id
setvard handmagic.anim $getcl(game.localplayer.viewmodel.active.id,anim)
setvard handmagic.event handmagic_connecthands
}
else if ( PARAM1 equals 'righthand' )
{
setvard magichand.on 1
setvard handmagic.handid game.localplayer.viewmodel.active.id
setvard handmagic.anim $getcl(game.localplayer.viewmodel.active.id,anim)
setvard handmagic.event handmagic_righthand
}
else
{
setvard magichand.on 0
}
}
{ handmagic_connecthands
if ( !PARAM1 )
{
callevent handmagic_createbeam 16 35
callevent handmagic_createbeam 19 38
callevent handmagic_createbeam 22 41
callevent handmagic_createbeam 25 44
callevent handmagic_createbeam 28 47
}
else
{
callevent create_sprite_2 1
callevent create_sprite_2 2
}
}
{ handmagic_righthand
if ( !PARAM1 )
{
callevent handmagic_createchargebeam 35 38
callevent handmagic_createchargebeam 38 41
callevent handmagic_createchargebeam 41 44
callevent handmagic_createchargebeam 44 47
}
else
{
callevent create_sprite_2 1
}
}
{ game_render_transparent
if magichand.on == 1
local l.continue 1
if ( game.localplayer.viewmodel.active.id != handmagic.handid ) local l.continue 0
if ( handmagic.anim != $getcl(game.localplayer.viewmodel.active.id,anim) ) local l.continue 0
if ( !l.continue ) callevent cl_handmagic_beam stop
if l.continue
callevent handmagic.event
local l.lightpos $getcl(game.localplayer.index,origin)
vectoradd l.lightpos (0,0,12)
cleffect light new l.lightpos LIGHT_RADIUS LIGHT_COLOR 0.01
}
{ handmagic_createbeam
local l.pos.left $getcl(handmagic.handid,bonepos,PARAM1)
local l.pos.right $getcl(handmagic.handid,bonepos,PARAM2)
cleffect beam_points l.pos.left l.pos.right SPRITE_LIGHTNING 0.001 0.1 0.1 0.3 0.1 30 (1,0.5,2)
}
{ handmagic_createchargebeam
if ( $rand(0,100) < 20 )
{
local l.pos.start $getcl(handmagic.handid,bonepos,PARAM1)
local l.pos.end $getcl(handmagic.handid,bonepos,PARAM2)
cleffect beam_points l.pos.start l.pos.end SPRITE_LIGHTNING 0.1 0.75 0.3 255 50 30 (120,200,255)
}
}
{ game_prerender
if magichand.on == 1
callevent handmagic.event 1
}
{ create_sprite_2
setvard magichand.attachment PARAM1
cleffect frameent sprite SPRITE_GLOW (0,0,0) setup_sprite_2
}
{ setup_sprite_2
cleffect frameent set_current_prop scale 0.25
cleffect frameent set_current_prop rendermode add
cleffect frameent set_current_prop renderamt 128
cleffect frameent set_current_prop rendercolor (0,0,255)
cleffect frameent set_current_prop follow handmagic.handid
cleffect frameent set_current_prop body magichand.attachment
}
